apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- application_datadog.yaml
- application_guestbook.yaml
- application_sealed-secrets.yaml
- application_sock-shop.yaml
- configmap_argocd-cmd-params-cm.yaml
- configmap_argocd-cm.yaml
- configmap_argocd-gpg-keys-cm.yaml
- configmap_argocd-notifications-cm.yaml
- configmap_argocd-rbac-cm.yaml
- configmap_argocd-redis-ha-configmap.yaml
- configmap_argocd-redis-ha-health-configmap.yaml
- configmap_argocd-ssh-known-hosts-cm.yaml
- configmap_argocd-tls-certs-cm.yaml
- deployment_argocd-applicationset-controller.yaml
- deployment_argocd-dex-server.yaml
- deployment_argocd-notifications-controller.yaml
- deployment_argocd-redis-ha-haproxy.yaml
- deployment_argocd-repo-server.yaml
- deployment_argocd-server.yaml
- networkpolicy_argocd-application-controller-network-policy.yaml
- networkpolicy_argocd-dex-server-network-policy.yaml
- networkpolicy_argocd-redis-ha-proxy-network-policy.yaml
- networkpolicy_argocd-redis-ha-server-network-policy.yaml
- networkpolicy_argocd-repo-server-network-policy.yaml
- networkpolicy_argocd-server-network-policy.yaml
- role_argocd-application-controller.yaml
- role_argocd-applicationset-controller.yaml
- role_argocd-dex-server.yaml
- role_argocd-notifications-controller.yaml
- role_argocd-redis-ha-haproxy.yaml
- role_argocd-redis-ha.yaml
- role_argocd-server.yaml
- rolebinding_argocd-application-controller.yaml
- rolebinding_argocd-applicationset-controller.yaml
- rolebinding_argocd-dex-server.yaml
- rolebinding_argocd-notifications-controller.yaml
- rolebinding_argocd-redis-ha-haproxy.yaml
- rolebinding_argocd-redis-ha.yaml
- rolebinding_argocd-server.yaml
- secret_argocd-notifications-secret.yaml
- secret_argocd-secret.yaml
- serviceaccount_argocd-application-controller.yaml
- serviceaccount_argocd-applicationset-controller.yaml
- serviceaccount_argocd-dex-server.yaml
- serviceaccount_argocd-notifications-controller.yaml
- serviceaccount_argocd-redis-ha-haproxy.yaml
- serviceaccount_argocd-redis-ha.yaml
- serviceaccount_argocd-repo-server.yaml
- serviceaccount_argocd-server.yaml
- service_argocd-applicationset-controller.yaml
- service_argocd-dex-server.yaml
- service_argocd-metrics.yaml
- service_argocd-notifications-controller-metrics.yaml
- service_argocd-redis-ha-announce-0.yaml
- service_argocd-redis-ha-announce-1.yaml
- service_argocd-redis-ha-announce-2.yaml
- service_argocd-redis-ha-haproxy.yaml
- service_argocd-redis-ha.yaml
- service_argocd-repo-server.yaml
- service_argocd-server-metrics.yaml
- service_argocd-server.yaml
- statefulset_argocd-application-controller.yaml
- statefulset_argocd-redis-ha-server.yaml
