apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-api-key
  namespace: default
spec:
  encryptedData:
    api-key: AgDAwkNhd8LXc9DHVQNlGr2paEEqLDiLlFTSwaracwXTA83D9eY/8eT+Vtns6IknHCt4UJDAkCH5epAlqAJ24w3NvQt3EuYm15YfbZHcRJkEuMnL9sffYFiQTn3NX0kd6xBQL0e4Yc0uOfuTanMFKB48bJfo/V9jzxJmbCTebKn9unGbdPkpvcqUp/sHc1lPXmLrfQBi7RB5XmIJdPLNDgcZn83+N2sfI6jmMd2zT6Puiusn4qXJF0jlFATJmtugRuCSWoIuuZEiqCsYlh+bUvzG+weNKPhA1ue0be8YPA6/cY3dcaVjW1sIivCRMAfI/Gwf3Cz9YXCWRCIpi4Ir/8Jep8PI944cvKB/R1PpbHMZi89uQNNUav6YxE/gh99nA0/RmqNtt64GjmT9JXK958OxbNeipIGFO/LO0+niwQ6ECn+oaqprHvqYus592BZTwAMjK6VzNsEPjELAWQCCGaEhZCvaHJyniC6VKKNwus3mbcnIjHOgH70aFoAQW4DIVDqOZkCl/agfNOrZZzrwmDO8vWkO9MNbw6EItUY99gIQvEQUYtTMuMq5RmHiLzk38f+8xA7UQhAdj84MvIB2Pemo/KLAXZ5RQjufG+GwIiwpT8UrwsgxgA4V2AGCgtuMNu52M0vQOrzqBbPVpMjjInMO21LmiPupFAkMe3UjOc8FpaFiMSbQzNsRs1UImlDvQyxBsK1eMph2chEd9G6ssJ5bMAUfZjtcPp2YhOyLEKa8JA==
    app-key: AgA4jHZDVQsik+0tSnupnLvxXBUIsqEaXtZ0CPEaNNyKSvhYbKjqPvLi199wyte4kPVkX2b8Ohj2/BuNqHZdt//mOyVygn2udkSDxACH0oMXp57cLHVQMhihTD0aCb6lLFR53UF+YGQDCFA/qiukWnehCa0ke3xHvUqORAO8uIue98ZnQg0EKUqhWnD2UebgCjOEcoWM9D7VpGJniQcvNJBfYZKgj+YK7h/afWJvdoazGzT8TZ6w1u84WpYnMSTES5ZlDhtqkbwlJx2vu3iH8InWpItOm3KvxIUGlIe/JhWRIlhHkRBUelqnpJDYk8AWSLLt7o6YMTzSyjlKMvwe9a3jgB7GNVtdYnG+2Iq3UiVxYk2DPSvvQEZP+SHEnfhIk69LqENXs1vyLXK/DUzWA0RJlAq7HNSYY2mDkfrm3ygUojAjV+0/iGKlg9l4PJYYh13/fsej3AREz3L8qgRMF5F99rgIJtpCeWHWoJIM9Q0hyGTx/5CimZ5V7ZJHNl2AUbwkgE5FG45oIAV2FUUuntN7tfyvl61+kM+U0quZ4RbZNZMs6cN4/XsON7csCqSHaoWYn08LmS++GHEcuN3ne+zldrVmOASn/d/5HP/7mSsPYjvGW/fD1ytiUuQ+TlCnahiCMuVJ6zp6tV7bRsDAAnKgePrF/xAu67iZYlabwvh1nOteq96c0LCB9PWKe8pHSnRd/wd5nW7CpId9MANWuNB4yIw3xmkDswugYZUL/wIL4RHHITJLxqZ3
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: datadog-api-key
      namespace: default

