apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-api-key
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgCi7aJgrugaszqOvcenYrmzDkTFX3z1VYglX6amia/FSn+PlfKACbFepUDIhhuGRWvczCiUi8sfadYWhXAmZaufXjswzg8S7HsOsq9qRNNWX1xIjPC1ADNtqKMwvVOWhi++BJc4qTBAO87ljdgRT08d5sc2xWw1oYDlFfNZ7VQcYvdz8rd1byIqcirg5qfmSj6WKdThqyQHCqTeSmR0/BchDvO5FsLZ/O6iYPt95GxFk7Q55BZRX70o1BCUCekoPoZjidKWzboPdoN9cbJcYtsr2PCtJcRhagvrbz15DDBccXIxmB2CQLc4l2QSlRmwqLmuFRIRpV4q9Sc1oM0rVfn0cteNl9I3AXvOCMPFOgWORjLnmwxi5ucimJaJSyTURkncMDLZH+qv0UhoRF70OsTq88F01HN+Eu/EFJZiqNwxRQy8mnyGBuXVor7PHlYMhZpTc7SXsL7bXoeLWbna9DV3F5JQegp2eOAMvuD7BC2ByZSxJMYH61BA9RfrY2Cjxc0L2+tb6QZWu8KldAPeWnJtUyMx04Mp+HIXUmniJv4MW/UqItjobhWu913y29mTfJ2vce0U0uw2kRINFe8xzIULOuXzkXC5T0sUemhjHFSR0KPiyUfRQfIFKVYCEujRTS0VjQA1szO5fmhEpGwuOSTJ04fDVIbSKkKrykj0oDdZTo3c2xA0naqYUy46KRiXkZr+lIgUR+L/32KYqq97XhQEw/2AtlW3gs1XlxInWZ/5Ow==
    app-key: AgCS0BTd1e676UjgkBvHSvgIoJPJgAgQ+ZeuiuihkWxv3EGOHKhofCzitDDKEjHnciTRK3kEhfz6uJcfXu+mqN8FjKIACFhYSD4dhKNAOySVIwN7SV9wyJfQFoBLr07fZiGYh+BWKAZ3byXpIn0+Sk5axZLR688fTM80FABH4dWUeO1ki/puRd+43YomXjliAvJmqbTuDkbiSYd4Ayb43e3Er82qsOk5QCGcQWInkWdDtKD/o2j28HLijgEWYfOIgiOCncrjWsWEpigiBLdZBQKByYuanKlOwqkuId/XZtRZfqDDmhFWGDF7KDCp1f94PJxzTK8qcSr0N7TSjffHz/XBPvc2a1rDyGa23U+f2Ep7KyT86n7A7HTrhlWNtzsi+F9kbymSwlufxp6nt41PkyEP0ojZvqH3yQH7Svntb0r81xNwdqgjCbs7tIEn26t6rntZgZ03led3AFRXrDVixPZKWGzUE7g6AS/2t9jA6GAG5C+BYWcKzryLtBtvlXcMfd4yAMA0uXW8JuR7TeKV+C71BzPR/DJs3b205WQzON2ToispG9zzCzZHTRu8y/p4/wFtPIQehQgxE7+7YYmZS4mJa/R3BWxuVpQzNoQVRHXo7Y/BusXEdmRV6VMYJ6LYnyR8/7nNz+4QqT/nSoftKHAjdhSWG0RZ3x7Wg7ntyFcXM1BRDMew9en7daQfOfJpg8f4fPl7Q6icPbQyK9sPLPHdD+cufk9ULEEBgO5claCg1zmPCkYpz2BL
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: datadog-api-key
      namespace: monitoring

