apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
spec:
  project: default
  source:
    repoURL: https://helm.datadoghq.com
    targetRevision: 2.33.7
    chart: datadog
    helm:
      values: |
        datadog:
          apiKeyExistingSecret: datadog-api-key
          appKeyExistingSecret: datadog-api-key
        clusterAgent:
          enabled: true
          metricsProvider:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: {}
