apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    configmanagement.gke.io/cluster-selector: selector-env-prod
spec:
  project: default
  source:
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
    helm:
      valueFiles: ["values-production.yaml"]
      values:
        image:
          pullPolicy: Always
  destination:
    server: "https://kubernetes.default.svc"
    namespace: guestbook
  syncPolicy:
    automated: {}
