apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argo-rollouts-notification-secret
  namespace: argo-rollouts
spec:
  encryptedData:
    slack-token: AgBiomAQkyFR5HiFagCUYKnl44onUS2NeWHkS1cWKQafiJ6hM6pVdxXihyop4CQtwg+UXdyqRyu9C51yBF2wRkqvUlzJ76hMevdXgElNT45fKZp34FTvVrVuleCL+qsD3Rqu4rsvAPo10QSsJ6MsDNO/gaIKJflqqMc20YJJNSzdt0znhb1GFZMzXUb4Q4EmdQ0WYJGmrEI2NI6Euj3Zxas1qN2OT/Su3kNnYVFxYDZvF9MaTV9fwhN00EEK5bOsY/TE/s2Sc9lmWLR0A72fWJQ6/JsMVVXEBSFWGw8D+mclAjB5MlHUjUItbucaglNmXsGkDVyBmPs0D3ID22f7G91H/7g8KRqdiMw7gE/NdPduJ0Lbyxh0lYzWfkY9Y//Ai0VXYZ56y9+Jza6TzBmReZO18wIDkFX2Ra9zhtXtH487unl3qnWidCl0V8f+ZlqT+fFJ0v+Qg7QvzUP3jagebMEtNclrYPOHEW66GjH0HCVcypO/hCVePkMj2/P4erbMvqjjitGT2NB9BDcr6Cxf1Qk12ipx1dMr/83TMv5FHL0r5ZnMzctGYcjq6wj6lSL5hvxF3LfcDmxIQc5OkWjy4Bf+fWdhC6GEt/COBCt4Ky15gMJUSgD1iUl2wpGmNniv8Ilh+do7LA5yOGOtgiBlqTNHwtKgsnLvGwqfiqIIRqL3k+UsH4R1JyUYBFxkG9JAbvQlIdXIdXTTDAOrfLg6gHVraCU2YFGUC4PzVnQJHFNMrmIJ4ybcTSlEiTyrHDA4JZLZWz5Z+VA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argo-rollouts-notification-secret
      namespace: argo-rollouts

