apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-api-key
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgBwEHg2y4c+Xp1KdNA5ijFDNZh/UohNaGBZHW1za3oGlyfvFMOOjbJXb9OUwU3B078cO1RtGh5O7T/DVHgLyEWYdqjRO0MR+/wrtxjUjWSyC4R2a7epyum+loDK8eIfjVS+1wxA1W+fiUM57vX3p3Wiymoa4/JfhpX7vg7WfYvuC0oEtWt9B5TFOFZeygQY1ds5iE5gwDmlna4ZfUur+a/e7CBIgrgpRT0SCqX6TxFy7vV9/sDfCahAv4tX/edaiE1SySX/DKKMXitsycRvKrwdO+ZBVMZhe1n3WeRbrtanLkqrGts0TEGrBE10M7V4DJYGivPUrfLaq3k7Gv8i5+ZdytyKVjG9Bf29WlvrYu5MdKeSole5Pz3SHENFtI2Jk1BpBiVRS1YjTShEPMr9zohj1d6ElxswfBKoKM82vc3Uq/VfQihYcMip6/LtXWZGl+R6ndUyC3nRjJ03vOVKtDoyuvAQqQXBtXMZxM71zUHtTCeA9OEn8me+52o8R0v8hL39yamMI5T5m8Aemi/dvlCvQ9x9u7i/SoZjCR2Km9BWuUz5vJYY66BcRVmqyAO284+fY53UjkG5xWd9ml+cbU65OLkOoMlRHi8uipuotSc09lqTroIRKEY9+oNFt2oBOckhm42GUdd4mXBdiMyg00u87ItLpeDrAVFNe0twpPOARnBCkHSnIWc4bTprEfYWBxSR5D95gwUXD09TBPB4Of43FTANSk1j50l/sTYZQanaLQ==
    app-key: AgC2QtB6HUXT4vhnCnGnDm+MGZHahrvCXmOlHwcPA6oDZSPlFHUMGlDNGqRdFdN+mLjR+bGk7fic7OJ349GXwscuJKD5JWOy14+zMjZEDQyBctfURR8yRTchqzN0TaIJE3guEqkKKcmyK3VP9Yrx+mtS7KQv0h64zbaPcDkSxfi3/ohJXgSRwfdDuz+zADk1+KlKXOf5VTRVBRulKNQUyxd1TRgFQcITiAN4dZ+MxACBu6ck8/hDvCFJMn77TSCUp9YQixblm6KuuuGxgSvRw086lr7bdyo6Tg6bBbsubC9TeMrCDLbxpyjH4Th/tt03iFpTWcTh3L6XCJKdIBlMZYGJvqwHuNdxfcwBxWvMHE8fkAOeTe3YcnlG8iR74p0O3jnwkfT71NgvX+Mv2yZHdelMB+i9HpmDDzSZe7dITStzU0lEHj1TxnMZ5Fu9x9u45jc4jrG1XNXO5nE6AqLjmKWJdijSVXQAIfcrdR3fa3xGanUaglc7Zi2zbn2t21ssDFLYGmXN+9u4bpQnMc2Nq/4Q84WAAe3BZtuHsfRvrnWJaA2uohTG759f8Tp50c+29N7KXpycS70qfv6aQgD+bi5QFekO2rIiZ0UHOyNmfNvw/bW85DhPOxzntJ+I3RkNSSljKNxGx5eKiSEAmQQICsIofIfhFfuRw0iQK2VbcaBk2vFyJelEQHn/TqSEU+j2LcRQ2kMdbLhijRWN5V73XlW5/bmy+kgUBNO7i8rMQRVoH/Xbp+dOnKbT
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: datadog-api-key
      namespace: monitoring

