---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datadog
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: datadog
    helm:
      values: |
        datadog:
          apiKeyExistingSecret: datadog-api-key
          appKeyExistingSecret: datadog-api-key
          logs:
            enabled: false
            containerCollectAll: true
          processAgent:
            enabled: true
            processCollection: true
          networkMonitoring:
            enabled: true
        clusterAgent:
          enabled: true
          metricsProvider:
            enabled: true
    repoURL: https://helm.datadoghq.com
    targetRevision: 2.33.7
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
