apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-api-key
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgAnqNLszTN4si+3EQlgghaTy63mERohSSMwDMTlPvbkEayrrf+1VOYqI2GEzYcW12qop3CJspXxTuhdnmuKSTDmDOlFtiCGHcUFe76cWpCNBrtzchy49gvqaILqLr8vkqRXnhN3vSoj2GfDl9x/Xt1tmdjqwlubiipRaytc47sgPZOuCt/W/5v3avT1/w/IR+edGMsf5gE5KXOd4ojR8qjYLTfvo4qXskBWZyU0CKSJkcBO+k5FOK3NNf7NzklJM4TZuTX9hzqaUdYKoG6miPocSQrFvP54sf7/UfTBUARP7M7hW5vChYDijbD5tPxiTiRqATL196+XMRDlL4IpDklhOtBWRK7r0uJoAjrXQm7XihXAg10nWZhEBSPODb5LsYz4DFHhaThMcXwDT23oJ4C3qWFxFKG3ofzZRZSMJf8XyfvrfXD14G+U4DOdhPkb1zYFEJAHJdFd2WvJXU1cC1plkkbSmyFm+41pw7InbVCin1j4tjsvqY8eFf9kKUv6mHWcC4xhuplqHlhqrFWYWjr8cvONTligAYlqdoeiNrxe9fFfwVxTSXrRAOE0vOrwJxGW4eWJy/nbSWqeuXsOoyPBvBuqTjXjUfXV/p4T/SGi6zJIHpWzB86CzPe2w8pbh3HRmA8rxVq8kRiPetHSyyYMt7EcvYOEvR2ECR+mGN3xAcv/EPIrvIk3bbPWr7cYR6Mqqiw8wfgBjopLfJnjHiHey0eef1yJiNotK9H+M4bHiQ==
    app-key: AgAvuEj2Xwavv9PGeXZi/X/1PsNLZljzzpXXsa85Cp8yarzQzFfL0sUn0bQGUPOwfSiN5Glpsott940DWdeOLAJMZuxPSU0fxFzaTZ+DYuzeWz+ylAfD89t1rg2Ffag6MoYm4pLDT7eoIJJYnwnjKaYalAsFrMXRsRJDPsqK6OL5LlCdMzpueuLpyNzuOh0nWTM7QMZLexwH9Z34l0Akm1UKuCHN/vZuDVauRMCMJsjAhZEy8oVQEy+7MWCm8dz9AX9vflWB6RAtm7n/gcfU8SSgGJxanMb0wLWNTHlK+Q2jdcd+R7F/cZfuUqIlMs4+Hn73CMzHCeFuA4p9xft+5VDeqfV3Nip6PrZW4hG4xYShIQDabJvkPuZjNBuBPmAQMZU/7E3T830YM66vhEHlLnZBpSYzSCmxDarg47h2/rZemKy1sNC9JZjUQmnr5Toi9pahX8c4lcT3mTe5bDCUydU+WQcPNT39BzJqZlmIEA2ujHb3dxX5WvslZw0pVhOiTUc/ajrn/OItUnMfEtrizBOaFePPM4yVCmMLsWPf0e33qyPdRup0xRRfPjCdugO3+hux8oHMCfyLUxzQa9L05+C6V/e/kwkkxxjm12FNjQpLtIZVgogUpI9ggPR5vLuQ1hOoqxrVTZPhtWQPMouy96tAl8QhOIFDvS3jMWHWqixwp+TDkRQlDpufuRezrgJCVY2v8pqiEHAekfmQaZUzlzZlJKKU+wK7iLJbsxpo/WozFjn057IQod8l
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: datadog-api-key
      namespace: monitoring

